import 'package:hive/hive.dart';

import 'counter.dart';

/// Hive TypeAdapter for [Counter].
///
/// Generated by `hive_generator`. Run:
///   flutter packages pub run build_runner build
/// to regenerate after model changes.
class CounterAdapter extends TypeAdapter<Counter> {
  @override
  final int typeId = 1;

  @override
  Counter read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Counter(
      id: fields[0] as String,
      label: fields[1] as String,
      currentValue: fields[2] as int? ?? 0,
      targetValue: fields[3] as int?,
      reminderEvery: fields[4] as int?,
      reminderNote: fields[5] as String?,
      isLocked: fields[6] as bool? ?? false,
    );
  }

  @override
  void write(BinaryWriter writer, Counter obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.label)
      ..writeByte(2)
      ..write(obj.currentValue)
      ..writeByte(3)
      ..write(obj.targetValue)
      ..writeByte(4)
      ..write(obj.reminderEvery)
      ..writeByte(5)
      ..write(obj.reminderNote)
      ..writeByte(6)
      ..write(obj.isLocked);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CounterAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
